
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-proxy
  namespace: node-proxy
  labels:
    app: node-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-proxy
  template:
    metadata:
      labels:
        app: node-proxy
    spec:
      containers:
        - name: node-proxy
          image: registry.gitlab.com/f5-public/node-proxy:v0.17
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PROXY_TARGET
              value: "http://aigw.ai-gateway.svc.cluster.local:80"
