mode: deployment
image:
  repository: "otel/opentelemetry-collector-contrib"
  tag: "0.112.0"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  exporters:

    prometheusremotewrite:
      endpoint: "http://prometheus-server.prometheus.svc.cluster.local:80/api/v1/write"
      tls:
        insecure: true

    otlp/jaeger:
      endpoint: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
      tls:
        insecure: true


  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp/jaeger]
      metrics:
        receivers: [otlp]
        exporters: [prometheusremotewrite]

